<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configurations>Debug;Release</Configurations>
    <Version>1.0.0</Version>
    <AssemblyName>SlopedIt</AssemblyName>
    <RootNamespace>SlopedIt</RootNamespace>
    <AssemblyTitle>Sloped It</AssemblyTitle>
    <Product>Sloped It</Product>
  </PropertyGroup>
  <Import Project="$(CSII_TOOLPATH)\Mod.props" />
  <Import Project="$(CSII_TOOLPATH)\Mod.targets" />
  <PropertyGroup>
    <UserDataPath>$(CSII_USERDATAPATH)</UserDataPath>
    <UnityModProjectPath>$(CSII_UNITYMODPROJECTPATH)</UnityModProjectPath>
    <ModPostProcessorPath>$(CSII_MODPOSTPROCESSORPATH)</ModPostProcessorPath>
    <ModPublisherPath>$(CSII_MODPUBLISHERPATH)</ModPublisherPath>
    <MSCORLIBPath>$(CSII_MSCORLIBPATH)</MSCORLIBPath>
    <LocalModsPath>$(MSBuildProjectDirectory)\..\local</LocalModsPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Game;Colossal.Core;Colossal.Logging;Colossal.IO.AssetDatabase;Colossal.Collections;Colossal.Mathematics;Colossal.Localization;Colossal.UI;Colossal.UI.Binding;UnityEngine.CoreModule;Unity.Collections;Unity.Entities;Unity.Mathematics">
      <Private>false</Private>
    </Reference>
    <Reference Update="System;System.Core;System.Data"><Private>false</Private></Reference>
  </ItemGroup>
  <Target Name="DeployWIP" AfterTargets="AfterBuild" Condition="'$(NeedBuild)'">
    <ItemGroup><FilesToDeploy Include="$(OutDir)\*.dll;$(OutDir)\*.pdb" /></ItemGroup>
    <MakeDir Directories="$(DeployDir)" />
    <Copy SourceFiles="@(FilesToDeploy)" DestinationFolder="$(DeployDir)" />
  </Target>
</Project>
